export const PROJECTS = [
    {
      id: 0,
      title:'Restaurant Con Fusion',
      subtitle: 'React.js',
      image: './images/react.jpg',
      category: 'frontend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      featured: false,     
      },
   {
      id: 1,
      title:'Code Snippets App',
      subtitle: 'Djangorestframework',
      image: './images/djangorest.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      featured: false,
      },
   {
      id: 2,
      title:'Ads Management',
      subtitle: 'Django',
      image: './images/dj-ads.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      featured: true,
      },
   {
      id: 3,
      title:'Con Fusion Restaurant',
      subtitle: 'Bootstrap-UI',
      image: './images/bootstrap.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      featured: false,                     
    },
    {
        id: 4,
        title:'Social-Media Posts',
        subtitle: 'FastAPI',
        image: './images/fastapi.jpg',
        category: 'backend',
        link: "https://reactbootcamp.com",
        gif: './images/bootstrap-con.gif',
        description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',   
        featured: false,                  
      }
]