export const PROJECTS = [
    {
      id: 0,
      title:'Restaurant Con Fusion',
      subtitle: 'Bootstrap UI',
      image: './images/react-conF.jpg',
      category: 'frontend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',     
      },
   {
      id: 1,
      title:'Code Snippets App',
      subtitle: 'Djangorestframework',
      image: './images/django-rest.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      },
   {
      id: 2,
      title:'Ads Management',
      subtitle: 'Django',
      image: './images/dj-ads.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',
      },
   {
      id: 3,
      title:'Con Fusion Restaurant',
      subtitle: 'Bootstrap-UI',
      image: './images/conF-bootstrap.jpg',
      category: 'backend',
      link: "https://reactbootcamp.com",
      gif: './images/bootstrap-con.gif',
      description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',                     
    },
    {
        id: 4,
        title:'Social-Media Posts',
        subtitle: 'Bootstrap-UI',
        image: './images/fast-API.jpg',
        category: 'backend',
        link: "https://reactbootcamp.com",
        gif: './images/bootstrap-con.gif',
        description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.',                     
      }
]